load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_test(
    name = "cfg_validator_test",
    srcs = ["cfg_validator.go"],
    visibility = ["//visibility:private"],
    deps = [
        "//cvl",
        "@com_github_pkg_profile//:go_default_library",
    ],
)

go_test(
    name = "cv_acl_test",
    srcs = ["cv_acl.go"],
    visibility = ["//visibility:private"],
    deps = [
        "//cvl",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_pkg_profile//:go_default_library",
    ],
)

go_test(
    name = "cv_edit_op_test",
    srcs = ["cv_edit_op.go"],
    visibility = ["//visibility:private"],
    deps = [
        "//cvl",
        "@com_github_pkg_profile//:go_default_library",
    ],
)

go_test(
    name = "cv_vlan_test",
    srcs = ["cv_vlan.go"],
    visibility = ["//visibility:private"],
    deps = [
        "//cvl",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_pkg_profile//:go_default_library",
    ],
)

go_library(
    name = "tests_lib",
    srcs = [
        "cfg_validator.go",
        "cv_acl.go",
        "cv_edit_op.go",
        "cv_vlan.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/cvl/tests",
    visibility = ["//visibility:private"],
    deps = [
        "//cvl",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_pkg_profile//:profile",
    ],
)

go_binary(
    name = "tests",
    embed = [":tests_lib"],
    visibility = ["//visibility:public"],
)
