load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "utils",
    srcs = [
        "bits.go",
        "utils.go",
        "ygr_meta.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/translib/utils",
    visibility = ["//visibility:public"],
    deps = [
        "//cvl",
        "//translib/db",
        "//translib/log",
        "//translib/ocbinds",
        "//translib/tlerr",
        "@com_github_golang_glog//:glog",
        "@com_github_golang_groupcache//lru",
        "@com_github_openconfig_ygot//ygot",
    ],
)

alias(
    name = "go_default_library",
    actual = ":utils",
    visibility = ["//visibility:public"],
)
