load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "custom_validation",
    srcs = [
        "common.go",
        "sonic_intf.go",
        "sonic_port_breakout.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/cvl/custom_validation",
    visibility = ["//visibility:public"],
    deps = [
        "//cvl/common",
        "//cvl/internal/util",
        "//cvl/internal/yparser",
        "//translib/log",
        "@com_github_antchfx_xmlquery//:xmlquery",
        "@com_github_golang_glog//:glog",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

alias(
    name = "go_default_library",
    actual = ":custom_validation",
    visibility = ["//visibility:public"],
)
