load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "apis",
    srcs = [
        "db_diff.go",
        "notify.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/translib/internal/apis",
    visibility = ["//translib:__subpackages__"],
    deps = [
        "//translib/db",
        "@com_github_openconfig_gnmi//proto/gnmi",
        "@com_github_openconfig_ygot//ygot",
    ],
)

alias(
    name = "go_default_library",
    actual = ":apis",
    visibility = ["//translib:__subpackages__"],
)

go_test(
    name = "apis_test",
    srcs = ["db_diff_test.go"],
    embed = [":apis"],
    deps = ["//translib/db"],
)
