load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "util",
    srcs = [
        "luascript_util.go",
        "util.go",
    ],
    cdeps = [
        "@com_github_cesnet_libyang//:libyang",
        "//:libyang_cgo_headers",
    ],
    cgo = True,
    # TODO BL: Fix this.
    # When consumed as an external module, includes from cc_library don't
    # propagate through cgo. Add the include path explicitly.
    cppopts = [
        "-isystem $(BINDIR)/external/sonic-mgmt-common+/libyang_headers_dir",
        "-isystem external/sonic-mgmt-common+/libyang_headers_dir",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/cvl/internal/util",
    visibility = ["//cvl:__subpackages__"],
    deps = [
        "//translib/log",
        "@com_github_golang_glog//:glog",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_workiva_go_datastructures//set",
    ],
)

alias(
    name = "go_default_library",
    actual = ":util",
    visibility = ["//cvl:__subpackages__"],
)
