load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "tlerr",
    srcs = [
        "app_errors.go",
        "tlerr.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/translib/tlerr",
    visibility = ["//visibility:public"],
    deps = [
        "//cvl",
        "//translib/log",
        "@com_github_golang_glog//:glog",
        "@org_golang_x_text//language",
        "@org_golang_x_text//message",
    ],
)

go_test(
    name = "tlerr_test",
    srcs = ["tlerr_test.go"],
    embed = [":tlerr"],
    visibility = ["//visibility:public"],
    deps = [
        "//cvl",
        "//translib/log",
    ],
)

alias(
    name = "go_default_library",
    actual = ":tlerr",
    visibility = ["//visibility:public"],
)
