load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "cvl",
    srcs = [
        "cvl.go",
        "cvl_api.go",
        "cvl_cache.go",
        "cvl_hint.go",
        "cvl_luascript.go",
        "cvl_semantics.go",
        "cvl_syntax.go",
    ],
    importpath = "github.com/Azure/sonic-mgmt-common/cvl",
    visibility = ["//visibility:public"],
    deps = [
        "//cvl/common",
        "//cvl/custom_validation",
        "//cvl/internal/util",
        "//cvl/internal/yparser",
        "@com_github_antchfx_jsonquery//:jsonquery",
        "@com_github_antchfx_xmlquery//:xmlquery",
        "@com_github_antchfx_xpath//:xpath",
        "@com_github_redis_go_redis_v9//:go-redis",
        "@com_github_google_go_cmp//cmp",
        "@com_github_philopon_go_toposort//:go-toposort",
    ],
)

go_test(
    name = "cvl_test",
    srcs = [
        "cvl_error_test.go",
        "cvl_hint_test.go",
        "cvl_leaflist_test.go",
        "cvl_leafref_test.go",
        "cvl_must_test.go",
        "cvl_test.go",
        "cvl_when_test.go",
        "jsondata_test.go",
    ],
    data = glob(["testdata/**"]),
    deps = [
        ":cvl",
        "//cvl/common",
        "//cvl/internal/util",
        "//translib/db",
        "//translib/tlerr",
        "@com_github_redis_go_redis_v9//:go-redis",
    ],
)

genrule(
    name = "yin-files",
    srcs = [
        "//models/yang:generate-yangs",
    ],
    outs = ["yin-files.tar"],
    cmd = "tar xf $(location //models/yang:generate-yangs) && " +
          "./$(location //cvl/tools:generate_yin) -v --path=yang --path=yang/sonic --out-dir=yin_file_build && " +
          "pushd yin_file_build && tar --owner=root --group=root -cf ../$(OUTS) *.yin && popd",
    tools = ["//cvl/tools:generate_yin"],
)

pkg_tar(
    name = "_schema",
    mode = "0755",
    package_dir = "/usr/sbin/schema",
    visibility = ["//visibility:private"],
    deps = [":yin-files"],
)

pkg_tar(
    name = "_conf",
    srcs = ["//cvl/conf:files"],
    mode = "0755",
    package_dir = "/usr/sbin",
    visibility = ["//visibility:private"],
)

pkg_tar(
    name = "cvl_tar",
    out = "cvl.tar",
    mode = "0755",
    deps = [
        ":_conf",
        ":_schema",
    ],
)

alias(
    name = "go_default_library",
    actual = ":cvl",
    visibility = ["//visibility:public"],
)
