load("@io_bazel_rules_go//go:def.bzl", "go_binary")

go_binary(
    name = "arloIssue29",
    srcs = ["arloIssue29.go"],
    data = [
        "//tools/test:database_config.json",
        "//cvl/conf:cvl_cfg.json",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//translib/db",
        "//translib/tlerr",
        "@com_github_golang_glog//:glog",
    ],
)

go_binary(
    name = "testdb",
    srcs = ["testdb.go"],
    data = [
        "//tools/test:database_config.json",
        "//cvl/conf:cvl_cfg.json",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//translib/db",
        "//translib/tlerr",
        "@com_github_golang_glog//:glog",
    ],
)

go_binary(
    name = "testmap",
    srcs = ["testmap.go"],
    data = [
        "//tools/test:database_config.json",
        "//cvl/conf:cvl_cfg.json",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//translib/db",
        "//translib/tlerr",
        "@com_github_golang_glog//:glog",
    ],
)

go_binary(
    name = "testsubscribe",
    srcs = ["testsubscribe.go"],
    data = [
        "//tools/test:database_config.json",
        "//cvl/conf:cvl_cfg.json",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//translib/db",
        "//translib/tlerr",
        "@com_github_golang_glog//:glog",
    ],
)
